name: Deploy Website

on:
  push: {}
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2

      - name: Install surge and fire deployment
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: npm
          cache-dependency-path: ./yarn.lock
      - run: npm install -g surge
      - run: npm install
      - run: npm run build
      - run: surge ./build --token ${{ secrets.SURGE_TOKEN }}

      - name: Linting
        run: npm run lint
      - name: Fixing lint
        run: npm run lint --fix
