name: Pull Request

on:
  push: {}
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    name: Codequality
    steps:
      - uses: actions/checkout@v2
      - name: Running Codequality
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
          cache-dependency-path: ./yarn.lock
      - run: npm install
      - run: npm run lint
